export const IPC_CHANNELS = {
  rendererToMain: {
    setWindowDirtyState: "nohal:set-window-dirty-state",
    readClipboardText: "nohal:read-clipboard-text",
    writeClipboardText: "nohal:write-clipboard-text",
    replySaveBeforeClose: "nohal:reply-save-before-close",
    promptUnsavedChanges: "nohal:prompt-unsaved-changes",
    getAppSettings: "nohal:get-app-settings",
    getCustomComponentStorePathInfo:
      "nohal:get-custom-component-store-path-info",
    updateAppSettings: "nohal:update-app-settings",
    newProject: "nohal:new-project",
    getRecentProjects: "nohal:get-recent-projects",
    openProject: "nohal:open-project",
    openProjectAt: "nohal:open-project-at",
    saveProject: "nohal:save-project",
    buildProject: "nohal:build-project",
    pickMachineIniFile: "nohal:pick-machine-ini-file",
    pickMachineHalFile: "nohal:pick-machine-hal-file",
    buildMachineConfigurationImport: "nohal:build-machine-configuration-import",
    importCompFile: "nohal:import-comp-file",
    pickCustomComponentStoreFile: "nohal:pick-custom-component-store-file",
    pickDirectory: "nohal:pick-directory",
    scanCompDir: "nohal:scan-comp-dir",
    loadComponentStore: "nohal:load-component-store",
    addManualComponentToStore: "nohal:add-manual-component-to-store",
    updateManualComponentInStore: "nohal:update-manual-component-in-store",
    removeManualComponentFromStore: "nohal:remove-manual-component-from-store",
    promoteProjectCustomComponentToStore:
      "nohal:promote-project-custom-component-to-store",
    importCompFileToStore: "nohal:import-comp-file-to-store",
    addCompDirSourceToStore: "nohal:add-comp-dir-source-to-store",
    refreshComponentSourceInStore: "nohal:refresh-component-source-in-store",
    deleteComponentSourceFromStore: "nohal:delete-component-source-from-store",
    refreshComponentInStore: "nohal:refresh-component-in-store",
    readTextFile: "nohal:read-text-file",
  },
  mainToRenderer: {
    requestSaveBeforeClose: "nohal:request-save-before-close",
  },
} as const;
