import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { exportProjectToHal } from "../shared/halExport";
import { slugify } from "../shared/id";
import type {
  LinuxCncIniDocument,
  LinuxCncIniEntry,
  NoHALProject,
} from "../shared/types";

interface GeneratedBuildFile {
  relativePath: string;
  content: string;
}

interface BuildManifest {
  format: "nohal-build-manifest";
  version: 1;
  files: string[];
}

export interface ProjectBuildResult {
  buildDir: string;
  files: string[];
  warnings: string[];
}

const BUILD_MANIFEST_FILENAME = ".nohal-build-manifest.json";

function normalizeBuildWarnings(warnings: string[]): string[] {
  return Array.from(
    new Set(warnings.map((warning) => warning.trim()).filter(Boolean)),
  );
}

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function formatIniEntry(entry: LinuxCncIniEntry): string {
  return `${entry.key} = ${entry.value}`;
}

function buildIniFileName(project: NoHALProject): string {
  const fallback = `${slugify(project.name)}.ini`;
  const sourceFileName = project.machineConfig?.ini.sourceFileName?.trim();
  if (!sourceFileName) return fallback;
  const base = path.basename(sourceFileName).trim();
  if (!base || base === "." || base === "..") return fallback;
  return base.toLowerCase().endsWith(".ini") ? base : `${base}.ini`;
}

function buildHalFileName(project: NoHALProject): string {
  return `${slugify(project.name)}.hal`;
}

function buildIniTextWithGeneratedHal(
  ini: LinuxCncIniDocument,
  halFileName: string,
  warnings: string[],
): string {
  const lines: string[] = [];
  let sawHalSection = false;
  let collapsedHalFileEntries = 0;
  let droppedPostguiEntries = 0;
  let droppedShutdownEntries = 0;

  lines.push("# Generated by NoHAL build");
  lines.push(`# HALFILE entries are consolidated to: ${halFileName}`);
  lines.push("");

  for (const section of ini.sections) {
    const isHalSection = section.name.toUpperCase() === "HAL";
    if (isHalSection) sawHalSection = true;

    lines.push(`[${section.name}]`);

    let insertedGeneratedHalRef = false;

    for (const entry of section.entries) {
      if (!isHalSection) {
        lines.push(formatIniEntry(entry));
        continue;
      }

      const keyUpper = entry.key.toUpperCase();
      if (keyUpper === "HALFILE") {
        collapsedHalFileEntries += 1;
        if (!insertedGeneratedHalRef) {
          lines.push(`HALFILE = ${halFileName}`);
          insertedGeneratedHalRef = true;
        }
        continue;
      }
      if (keyUpper === "POSTGUI_HALFILE") {
        droppedPostguiEntries += 1;
        continue;
      }
      if (keyUpper === "SHUTDOWN") {
        droppedShutdownEntries += 1;
        continue;
      }

      lines.push(formatIniEntry(entry));
    }

    if (isHalSection && !insertedGeneratedHalRef) {
      lines.push(`HALFILE = ${halFileName}`);
    }

    lines.push("");
  }

  if (!sawHalSection) {
    lines.push("[HAL]");
    lines.push(`HALFILE = ${halFileName}`);
    lines.push("");
    warnings.push("Build INI added a missing [HAL] section with one HALFILE.");
  }

  if (collapsedHalFileEntries > 1) {
    warnings.push(
      `Build INI collapsed ${collapsedHalFileEntries} HALFILE entries into one generated HALFILE.`,
    );
  }
  if (droppedPostguiEntries > 0) {
    warnings.push(
      `Build INI omitted ${droppedPostguiEntries} POSTGUI_HALFILE entr${droppedPostguiEntries === 1 ? "y" : "ies"} (separate postgui build output is not implemented yet).`,
    );
  }
  if (droppedShutdownEntries > 0) {
    warnings.push(
      `Build INI omitted ${droppedShutdownEntries} SHUTDOWN entr${droppedShutdownEntries === 1 ? "y" : "ies"} (shutdown script build output is not implemented yet).`,
    );
  }

  return `${lines.join("\n")}\n`;
}

function createGeneratedBuildFiles(project: NoHALProject): {
  files: GeneratedBuildFile[];
  warnings: string[];
} {
  const warnings: string[] = [];
  const files: GeneratedBuildFile[] = [];
  const halFileName = buildHalFileName(project);

  const hal = exportProjectToHal(project);
  warnings.push(...hal.warnings);
  files.push({
    relativePath: halFileName,
    content: hal.text,
  });

  const machineConfig = project.machineConfig;
  const ini = machineConfig?.ini;
  if (!ini || ini.sections.length === 0) {
    warnings.push(
      "Build output contains generated HAL only (no imported machine INI is available in this project).",
    );
    return { files, warnings: normalizeBuildWarnings(warnings) };
  }

  const unsupportedSources = machineConfig.halSources.filter(
    (source) =>
      source.status === "missing" ||
      source.status === "skipped-lib" ||
      source.status === "skipped-non-hal",
  );
  if (unsupportedSources.length > 0) {
    warnings.push(
      `Imported machine config had ${unsupportedSources.length} HAL source reference${unsupportedSources.length === 1 ? "" : "s"} that are not reproduced as separate build outputs.`,
    );
  }

  files.push({
    relativePath: buildIniFileName(project),
    content: buildIniTextWithGeneratedHal(ini, halFileName, warnings),
  });

  return { files, warnings: normalizeBuildWarnings(warnings) };
}

function assertSafeRelativeBuildPath(relativePath: string): void {
  const normalized = relativePath.replace(/\\/g, "/");
  const parts = normalized.split("/").filter(Boolean);
  if (
    normalized.startsWith("/") ||
    parts.length === 0 ||
    parts.some((part) => part === "." || part === "..")
  ) {
    throw new Error(`Invalid build output path: ${relativePath}`);
  }
}

function isBuildManifestLike(value: unknown): value is BuildManifest {
  if (!value || typeof value !== "object") return false;
  const manifest = value as Partial<BuildManifest>;
  return (
    manifest.format === "nohal-build-manifest" &&
    manifest.version === 1 &&
    Array.isArray(manifest.files) &&
    manifest.files.every((file) => typeof file === "string")
  );
}

async function readBuildManifest(buildDir: string): Promise<BuildManifest | null> {
  const manifestPath = path.join(buildDir, BUILD_MANIFEST_FILENAME);
  try {
    const text = await readFile(manifestPath, "utf8");
    const parsed = JSON.parse(text) as unknown;
    return isBuildManifestLike(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

async function removeStaleGeneratedFiles(
  buildDir: string,
  nextRelativePaths: Set<string>,
): Promise<void> {
  const previousManifest = await readBuildManifest(buildDir);
  if (!previousManifest) return;

  for (const relativePath of previousManifest.files) {
    try {
      assertSafeRelativeBuildPath(relativePath);
    } catch {
      continue;
    }
    if (nextRelativePaths.has(relativePath)) continue;
    try {
      await unlink(path.join(buildDir, relativePath));
    } catch {
      // Best-effort cleanup; build should still succeed.
    }
  }
}

export async function buildProjectIntoDirectory(
  project: NoHALProject,
  projectDir: string,
): Promise<ProjectBuildResult> {
  const buildDir = path.join(path.resolve(projectDir), "build");
  await mkdir(buildDir, { recursive: true });

  const generated = createGeneratedBuildFiles(project);
  const writtenFiles: string[] = [];
  const nextRelativePaths = new Set(generated.files.map((file) => file.relativePath));

  await removeStaleGeneratedFiles(buildDir, nextRelativePaths);

  for (const file of generated.files) {
    assertSafeRelativeBuildPath(file.relativePath);
    const outputPath = path.join(buildDir, file.relativePath);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, file.content, "utf8");
    writtenFiles.push(outputPath);
  }

  await writeFile(
    path.join(buildDir, BUILD_MANIFEST_FILENAME),
    stringifyJson({
      format: "nohal-build-manifest",
      version: 1,
      files: generated.files.map((file) => file.relativePath),
    } satisfies BuildManifest),
    "utf8",
  );

  return {
    buildDir,
    files: writtenFiles,
    warnings: generated.warnings,
  };
}
