import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createEmptyProject } from "../shared/project";
import type { NoHALProject } from "../shared/types";
import { buildProjectIntoDirectory } from "./projectBuild";

const tempDirs: string[] = [];

async function makeTempDir(prefix = "nohal-build-test-"): Promise<string> {
  const dir = await mkdtemp(path.join(os.tmpdir(), prefix));
  tempDirs.push(dir);
  return dir;
}

afterEach(async () => {
  await Promise.all(
    tempDirs
      .splice(0, tempDirs.length)
      .map((dir) => rm(dir, { recursive: true, force: true })),
  );
});

function withImportedIni(project: NoHALProject): NoHALProject {
  return {
    ...project,
    machineConfig: {
      source: "imported-linuxcnc-config",
      ini: {
        parser: "nohal-ini-v1",
        sourcePath: "/machines/demo/demo.ini",
        sourceFileName: "demo.ini",
        lineCount: 8,
        warnings: [],
        sections: [
          {
            name: "EMC",
            line: 1,
            entries: [{ key: "MACHINE", value: "Demo", line: 2 }],
          },
          {
            name: "HAL",
            line: 4,
            entries: [
              { key: "HALFILE", value: "core.hal", line: 5 },
              { key: "HALFILE", value: "io.hal", line: 6 },
              { key: "POSTGUI_HALFILE", value: "postgui.hal", line: 7 },
              { key: "SHUTDOWN", value: "shutdown.hal", line: 8 },
              { key: "TWOPASS", value: "on", line: 9 },
            ],
          },
        ],
      },
      halSources: [],
    },
  };
}

describe("project build output", () => {
  it("writes generated HAL into a build directory for a blank project", async () => {
    const project = createEmptyProject("Blank Build Test");
    const projectDir = path.join(await makeTempDir(), "blank.nohal");

    const result = await buildProjectIntoDirectory(project, projectDir);

    expect(result.buildDir).toBe(path.join(projectDir, "build"));
    expect(result.files).toEqual([
      path.join(projectDir, "build", "blank-build-test.hal"),
    ]);
    expect(result.warnings).toContain(
      "Build output contains generated HAL only (no imported machine INI is available in this project).",
    );

    const halText = await readFile(
      path.join(result.buildDir, "blank-build-test.hal"),
      "utf8",
    );
    expect(halText).toContain("# NoHAL HAL export");
    expect(halText).toContain("# Project: Blank Build Test");
  });

  it("writes a generated INI that points to generated.hal for imported machine configs", async () => {
    const project = withImportedIni(createEmptyProject("Imported Build Test"));
    const projectDir = path.join(await makeTempDir(), "imported.nohal");

    const result = await buildProjectIntoDirectory(project, projectDir);

    expect(result.files).toEqual(
      expect.arrayContaining([
        path.join(projectDir, "build", "imported-build-test.hal"),
        path.join(projectDir, "build", "demo.ini"),
      ]),
    );

    const iniText = await readFile(
      path.join(projectDir, "build", "demo.ini"),
      "utf8",
    );
    expect(iniText).toContain("# Generated by NoHAL build");
    expect(iniText).toContain("[HAL]");
    expect(iniText).toContain("HALFILE = imported-build-test.hal");
    expect(iniText).toContain("TWOPASS = on");
    expect(iniText).not.toContain("core.hal");
    expect(iniText).not.toContain("io.hal");
    expect(iniText).not.toContain("POSTGUI_HALFILE");
    expect(iniText).not.toContain("SHUTDOWN =");

    expect(result.warnings).toContain(
      "Build INI collapsed 2 HALFILE entries into one generated HALFILE.",
    );
    expect(
      result.warnings.some((warning) => warning.includes("POSTGUI_HALFILE")),
    ).toBe(true);
    expect(
      result.warnings.some((warning) => warning.includes("SHUTDOWN")),
    ).toBe(true);
  });

  it("removes stale generated outputs from previous builds when output names change", async () => {
    const projectDir = path.join(await makeTempDir(), "rename.nohal");
    const firstProject = createEmptyProject("Machine Alpha");
    await buildProjectIntoDirectory(firstProject, projectDir);

    const firstOutput = path.join(projectDir, "build", "machine-alpha.hal");
    expect(await readFile(firstOutput, "utf8")).toContain(
      "# Project: Machine Alpha",
    );

    const renamedProject: NoHALProject = {
      ...firstProject,
      name: "Machine Beta",
    };
    await buildProjectIntoDirectory(renamedProject, projectDir);

    const secondOutput = path.join(projectDir, "build", "machine-beta.hal");
    expect(await readFile(secondOutput, "utf8")).toContain(
      "# Project: Machine Beta",
    );
    await expect(readFile(firstOutput, "utf8")).rejects.toThrow();
  });
});
