import { filter, map, pipe, unique } from "remeda";
import { exportProjectToHal } from "../halExport";
import { slugify } from "../id";
import {
  buildEffectiveMachineConfigIni,
  buildManagedMachineConfigIniSections,
} from "../machineConfig/policy";
import type {
  CoreIo,
  LinuxCncIniDocument,
  LinuxCncIniEntry,
  NoHALProject,
} from "../types";
import {
  NOHAL_BUILD_MANIFEST_FORMAT,
  NOHAL_BUILD_MANIFEST_VERSION,
} from "./formats";

interface GeneratedBuildFile {
  relativePath: string;
  content: string;
}

interface BuildManifest {
  format: typeof NOHAL_BUILD_MANIFEST_FORMAT;
  version: typeof NOHAL_BUILD_MANIFEST_VERSION;
  files: string[];
}

export interface ProjectBuildResult {
  buildDir: string;
  files: string[];
  warnings: string[];
}

export interface ProjectBuildApi {
  buildProjectIntoDirectory(
    project: NoHALProject,
    projectDir: string,
  ): Promise<ProjectBuildResult>;
}

const BUILD_MANIFEST_FILENAME = ".nohal-build-manifest.json";

function normalizeBuildWarnings(warnings: string[]): string[] {
  return pipe(
    warnings,
    map((warning) => warning.trim()),
    filter(Boolean),
    unique(),
  );
}

function stringifyJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function formatIniEntry(entry: LinuxCncIniEntry): string {
  return `${entry.key} = ${entry.value}`;
}

const buildIniFileName =
  (io: CoreIo) =>
  (project: NoHALProject): string => {
    const fallback = `${slugify(project.name)}.ini`;
    const sourceFileName =
      project.machineConfig?.userIni.sourceFileName?.trim();
    if (!sourceFileName) return fallback;
    const base = io.path.basename(sourceFileName).trim();
    if (!base || base === "." || base === "..") return fallback;
    return base.toLowerCase().endsWith(".ini") ? base : `${base}.ini`;
  };

function buildIniText(ini: LinuxCncIniDocument): string {
  const lines: string[] = [];

  lines.push("# Generated by NoHAL build");
  lines.push("");

  for (const section of ini.sections) {
    lines.push(`[${section.name}]`);
    for (const entry of section.entries) {
      lines.push(formatIniEntry(entry));
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function buildProjectIni(project: NoHALProject): LinuxCncIniDocument {
  const effectiveIni = buildEffectiveMachineConfigIni(project);
  if (effectiveIni) return effectiveIni;
  return {
    parser: "nohal-ini-v1",
    lineCount: 0,
    warnings: [],
    sections: buildManagedMachineConfigIniSections(project),
  };
}

const createGeneratedBuildFiles =
  (io: CoreIo) =>
  (
    project: NoHALProject,
  ): {
    files: GeneratedBuildFile[];
    warnings: string[];
  } => {
    const warnings: string[] = [];
    const files: GeneratedBuildFile[] = [];

    const hal = exportProjectToHal(project);
    warnings.push(...hal.warnings);
    files.push({
      relativePath: `${slugify(project.name)}.hal`,
      content: hal.text,
    });
    if (hal.postguiText) {
      files.push({
        relativePath: `${slugify(project.name)}-postgui.hal`,
        content: hal.postguiText,
      });
    }
    if (hal.shutdownText) {
      files.push({
        relativePath: `${slugify(project.name)}-shutdown.hal`,
        content: hal.shutdownText,
      });
    }

    const machineConfig = project.machineConfig;
    const unsupportedSources = (machineConfig?.halSources ?? []).filter(
      (source) =>
        source.status === "missing" ||
        source.status === "skipped-lib" ||
        source.status === "skipped-non-hal",
    );
    if (unsupportedSources.length > 0) {
      warnings.push(
        `Machine config had ${unsupportedSources.length} HAL source reference${unsupportedSources.length === 1 ? "" : "s"} that are not reproduced as separate build outputs.`,
      );
    }

    files.push({
      relativePath: buildIniFileName(io)(project),
      content: buildIniText(buildProjectIni(project)),
    });

    return { files, warnings: normalizeBuildWarnings(warnings) };
  };

function assertSafeRelativeBuildPath(relativePath: string): void {
  const normalized = relativePath.replace(/\\/g, "/");
  const parts = normalized.split("/").filter(Boolean);
  if (
    normalized.startsWith("/") ||
    parts.length === 0 ||
    parts.some((part) => part === "." || part === "..")
  ) {
    throw new Error(`Invalid build output path: ${relativePath}`);
  }
}

function isBuildManifestLike(value: unknown): value is BuildManifest {
  if (!value || typeof value !== "object") return false;
  const manifest = value as Partial<BuildManifest>;
  return (
    manifest.format === NOHAL_BUILD_MANIFEST_FORMAT &&
    manifest.version === NOHAL_BUILD_MANIFEST_VERSION &&
    Array.isArray(manifest.files) &&
    manifest.files.every((file) => typeof file === "string")
  );
}

const readBuildManifest =
  (io: CoreIo) =>
  async (buildDir: string): Promise<BuildManifest | null> => {
    const manifestPath = io.path.join(buildDir, BUILD_MANIFEST_FILENAME);
    try {
      const text = await io.fs.readTextFile(manifestPath);
      const parsed = JSON.parse(text) as unknown;
      return isBuildManifestLike(parsed) ? parsed : null;
    } catch {
      return null;
    }
  };

const removeStaleGeneratedFiles =
  (io: CoreIo) =>
  async (buildDir: string, nextRelativePaths: Set<string>): Promise<void> => {
    const previousManifest = await readBuildManifest(io)(buildDir);
    if (!previousManifest) return;

    for (const relativePath of previousManifest.files) {
      try {
        assertSafeRelativeBuildPath(relativePath);
      } catch {
        continue;
      }
      if (nextRelativePaths.has(relativePath)) continue;
      try {
        await io.fs.removeFile(io.path.join(buildDir, relativePath));
      } catch {
        // Best-effort cleanup; build should still succeed.
      }
    }
  };

export const buildProjectIntoDirectory = (io: CoreIo) => {
  const createGeneratedBuildFilesWithIo = createGeneratedBuildFiles(io);
  const removeStaleGeneratedFilesWithIo = removeStaleGeneratedFiles(io);

  return async (
    project: NoHALProject,
    projectDir: string,
  ): Promise<ProjectBuildResult> => {
    const buildDir = io.path.join(io.path.resolve(projectDir), "build");
    await io.fs.makeDir(buildDir, { recursive: true });

    const generated = createGeneratedBuildFilesWithIo(project);
    const writtenFiles: string[] = [];
    const nextRelativePaths = new Set(
      generated.files.map((file) => file.relativePath),
    );

    await removeStaleGeneratedFilesWithIo(buildDir, nextRelativePaths);

    for (const file of generated.files) {
      assertSafeRelativeBuildPath(file.relativePath);
      const outputPath = io.path.join(buildDir, file.relativePath);
      await io.fs.makeDir(io.path.dirname(outputPath), { recursive: true });
      await io.fs.writeTextFile(outputPath, file.content);
      writtenFiles.push(outputPath);
    }

    await io.fs.writeTextFile(
      io.path.join(buildDir, BUILD_MANIFEST_FILENAME),
      stringifyJson({
        format: NOHAL_BUILD_MANIFEST_FORMAT,
        version: NOHAL_BUILD_MANIFEST_VERSION,
        files: generated.files.map((file) => file.relativePath),
      } satisfies BuildManifest),
    );

    return {
      buildDir,
      files: writtenFiles,
      warnings: generated.warnings,
    };
  };
};

export function createProjectBuildApi(io: CoreIo): ProjectBuildApi {
  return {
    buildProjectIntoDirectory: buildProjectIntoDirectory(io),
  };
}
