import { describe, expect, it } from "vitest";
import { createMemoryIo } from "../testUtils/memoryIo";
import type { NoHALProject } from "../types";
import { buildProjectIntoDirectory as buildProjectIntoDirectoryWithIo } from "./build";
import { createEmptyProject } from "./project";

function withImportedIni(project: NoHALProject): NoHALProject {
  return {
    ...project,
    machineConfig: {
      source: "imported-linuxcnc-config",
      ini: {
        parser: "nohal-ini-v1",
        sourcePath: "/machines/demo/demo.ini",
        sourceFileName: "demo.ini",
        lineCount: 8,
        warnings: [],
        sections: [
          {
            name: "EMC",
            line: 1,
            entries: [{ key: "MACHINE", value: "Demo", line: 2 }],
          },
          {
            name: "HAL",
            line: 4,
            entries: [
              { key: "HALFILE", value: "core.hal", line: 5 },
              { key: "HALFILE", value: "io.hal", line: 6 },
              { key: "POSTGUI_HALFILE", value: "postgui.hal", line: 7 },
              { key: "SHUTDOWN", value: "shutdown.hal", line: 8 },
              { key: "TWOPASS", value: "on", line: 9 },
            ],
          },
        ],
      },
      halSources: [],
    },
  };
}

describe("project build output", () => {
  it("writes generated HAL into a build directory for a blank project", async () => {
    const { io, readFile } = createMemoryIo();
    const buildProjectIntoDirectory = buildProjectIntoDirectoryWithIo(io);
    const project = createEmptyProject("Blank Build Test");
    const projectDir = io.path.resolve("/tests", "blank.nohal");

    const result = await buildProjectIntoDirectory(project, projectDir);

    expect(result.buildDir).toBe(io.path.join(projectDir, "build"));
    expect(result.files).toEqual([
      io.path.join(projectDir, "build", "blank-build-test.hal"),
    ]);
    expect(result.warnings).toContain(
      "Build output contains generated HAL only (no imported machine INI is available in this project).",
    );

    const halText = await readFile(
      io.path.join(result.buildDir, "blank-build-test.hal"),
    );
    expect(halText).toContain("# NoHAL HAL export");
    expect(halText).toContain("# Project: Blank Build Test");
  });

  it("writes a generated INI that points to generated.hal for imported machine configs", async () => {
    const { io, readFile } = createMemoryIo();
    const buildProjectIntoDirectory = buildProjectIntoDirectoryWithIo(io);
    const project = withImportedIni(createEmptyProject("Imported Build Test"));
    const projectDir = io.path.resolve("/tests", "imported.nohal");

    const result = await buildProjectIntoDirectory(project, projectDir);

    expect(result.files).toEqual(
      expect.arrayContaining([
        io.path.join(projectDir, "build", "imported-build-test.hal"),
        io.path.join(projectDir, "build", "demo.ini"),
      ]),
    );

    const iniText = await readFile(
      io.path.join(projectDir, "build", "demo.ini"),
    );
    expect(iniText).toContain("# Generated by NoHAL build");
    expect(iniText).toContain("[HAL]");
    expect(iniText).toContain("HALFILE = imported-build-test.hal");
    expect(iniText).toContain("TWOPASS = on");
    expect(iniText).not.toContain("core.hal");
    expect(iniText).not.toContain("io.hal");
    expect(iniText).not.toContain("POSTGUI_HALFILE");
    expect(iniText).not.toContain("SHUTDOWN =");

    expect(result.warnings).toContain(
      "Build INI collapsed 2 HALFILE entries into one generated HALFILE.",
    );
    expect(
      result.warnings.some((warning) => warning.includes("POSTGUI_HALFILE")),
    ).toBe(true);
    expect(
      result.warnings.some((warning) => warning.includes("SHUTDOWN")),
    ).toBe(true);
  });

  it("writes generated postgui HAL and POSTGUI_HALFILE when postgui stage nodes are present", async () => {
    const { io, readFile } = createMemoryIo();
    const buildProjectIntoDirectory = buildProjectIntoDirectoryWithIo(io);
    const project = withImportedIni(createEmptyProject("Postgui Build Test"));
    const rootSheet = project.sheets[project.rootSheetId];
    project.library.components["comp:test-and2"] = {
      id: "comp:test-and2",
      name: "and2",
      halComponentName: "and2",
      source: "comp",
      runtime: { kind: "rt" },
      pins: [
        { key: "in0", name: "in0", direction: "in", type: "bit" },
        { key: "in1", name: "in1", direction: "in", type: "bit" },
        { key: "out", name: "out", direction: "out", type: "bit" },
      ],
      params: [],
    };
    rootSheet.nodes.push({
      id: "node_pg",
      kind: "component",
      componentId: "comp:test-and2",
      instanceName: "and2.0",
      position: { x: 0, y: 0 },
      paramValues: {},
      pinInitialValues: { in0: "1" },
      exportStage: "postgui",
    });
    const projectDir = io.path.resolve("/tests", "postgui.nohal");

    const result = await buildProjectIntoDirectory(project, projectDir);

    expect(result.files).toEqual(
      expect.arrayContaining([
        io.path.join(projectDir, "build", "postgui-build-test.hal"),
        io.path.join(projectDir, "build", "postgui-build-test-postgui.hal"),
        io.path.join(projectDir, "build", "demo.ini"),
      ]),
    );

    const iniText = await readFile(
      io.path.join(projectDir, "build", "demo.ini"),
    );
    expect(iniText).toContain("HALFILE = postgui-build-test.hal");
    expect(iniText).toContain(
      "POSTGUI_HALFILE = postgui-build-test-postgui.hal",
    );
    expect(iniText).not.toContain("POSTGUI_HALFILE = postgui.hal");
  });

  it("removes stale generated outputs from previous builds when output names change", async () => {
    const { io, readFile } = createMemoryIo();
    const buildProjectIntoDirectory = buildProjectIntoDirectoryWithIo(io);
    const projectDir = io.path.resolve("/tests", "rename.nohal");
    const firstProject = createEmptyProject("Machine Alpha");
    await buildProjectIntoDirectory(firstProject, projectDir);

    const firstOutput = io.path.join(projectDir, "build", "machine-alpha.hal");
    expect(await readFile(firstOutput)).toContain("# Project: Machine Alpha");

    const renamedProject: NoHALProject = {
      ...firstProject,
      name: "Machine Beta",
    };
    await buildProjectIntoDirectory(renamedProject, projectDir);

    const secondOutput = io.path.join(projectDir, "build", "machine-beta.hal");
    expect(await readFile(secondOutput)).toContain("# Project: Machine Beta");
    await expect(readFile(firstOutput)).rejects.toThrow();
  });
});
